
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: gestorproyectos
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: adminpassword
      DB_NAME: gestorproyectos
      SECRET_JWT_KEY: esto-es-una-secret-key-muypoco-larga-y-segura-11-33-42
      NODE_ENV: production
    ports:
      - "4000:4000"
    depends_on:
      - database
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:4000
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge